version: '3'

services:
  web:
    image: php:apache
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
      - mailpit

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: spmb-laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
